### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by ffrm** [ffrm/react-native-forms#1]
- [ ] Scroll window to focused field when keyboard opens
- [ ] Add validation style when user submits/completes the mask
- [ ] Optional text for invalid fields
