### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by asnando** [ffrm/react-native-forms#6]
# Todo

### General
- [x] Add field validators (like e-mail validator functions)
- [x] Make form tabulation behavior
- [x] Handle form scroll fields position

### Steps
- [x] Conditionally show step fields based on previous fields values

### Wontfix
- [ ] Block submit button when "submitting" Form prop is true
- [ ] Support style object to apply when field is (in)valid
- [ ] DatePicker field type
